---
title: "BloodDataWithLME4"
author: "Kevin O'Brien"
date: "Monday, August 24, 2015"
output: html_document
---
```{r}
#using package NLME
library(nlme)
library(lme4)
source("data/BloodData.R")
```
### Working on the JS comparison
```{r}
blood = groupedData( BP ~ method | subject ,
  data = data.frame( BP = c(Blood), 
    subject = rep(seq(nrow(Blood)), ncol(Blood)),
    method = rep(c("J","R","S"), rep(nrow(Blood)*3, 3)),
		repl = rep(rep(c(1:3), rep(nrow(Blood), 3)), 3) ),
	labels = list(BP = "Systolic Blood Pressure", method = "Measurement Device"),
	)
```

```{r}
roy.LME4 = lmer(BP ~ method-1 + (1 |subject ), data = blood,REML = FALSE)
summary(roy.LME4)
#intervals(roy.LME4a)
```

```{r}

plot(roy.LME4)

```



```{r}

roy.NLME <-lme(BP ~ method-1 , random=~1|subject,data = blood)
summary(roy.NLME)
intervals(roy.NLME)

```
```{r}
plot(roy.NLME, resid(., type = "p") ~ fitted(.) | method, abline = 0, id=.05)
```

```{r}
library(influence.ME)
```
```{r}
grouping.levels(roy.LME4, "subject")
```
```{r}
roy.LME4.inf  <- influence(roy.LME4, "subject")

```
```{r}
CDs<- cooks.distance(roy.LME4.inf)
```
```{r}
subjectnames<- rownames(cooks.distance(roy.LME4.inf))
CDdf <- data.frame(subjectnames,CDs)
```
```{r}
library(dplyr)
CDdf<- arrange(CDdf,desc(CDs))
head(CDdf)

```
```{r}
dfbeta <- dfbetas(roy.LME4.inf)
subjectnames <- rownames(dfbetas(roy.LME4.inf))
DFBetadf <- data.frame(subjectnames,dfbeta)
```
```{r}
Infldf <- inner_join(CDdf,DFBetadf)
Infldf<- arrange(Infldf,desc(CDs))
head(Infldf)
```
This plot is very simple to interpret. If the points align on the line of equality, the respective methods can be said to be in agreement.
If is worth noting that it does really on complex calculations.

If two methods of measurement are in agreement, the DFbeta for each case should be more or less the same for both.

```{r}
plot(Infldf$methodJ,Infldf$methodR,col="red",pch=16)
abline(c(0,1))
```

```{r}
plot(Infldf$methodJ,Infldf$methodS,col="red",pch=16)
abline(c(0,1))
```
```{r}
plot(Infldf$methodR,Infldf$methodS,col="red",pch=16)
abline(c(0,1))
```
```{r}

dim(blood)

blood.red <- blood[!(blood$subject %in% c(68,78,80)),]
dim(blood.red)
```

```{r}
round(dfbetas(roy.LME4.inf),4)
```


```{r}

roy.NLME.red <-lme(BP ~ method-1 , random=~1|subject,data = blood.red)
summary(roy.NLME.red)
intervals(roy.NLME.red)

```
```{r}
plot(roy.NLME.red, resid(., type = "p") ~ fitted(.) | method, abline = 0, id=.05)
```
