---
title: "10-PermutationTests"
author: "Kevin O'Brien"
date: "Saturday, August 29, 2015"
output: html_document
---
```{r}
#using package NLME
library(nlme)
library(predictmeans)
source("data/BloodData.R")
```

### Working on the JS comparison
```{r}
blood = groupedData( BP ~ method | subject ,
  data = data.frame( BP = c(Blood), 
    subject = rep(seq(nrow(Blood)), ncol(Blood)),
  	method = rep(c("J","R","S"), rep(nrow(Blood)*3, 3)),
		repl = rep(rep(c(1:3), rep(nrow(Blood), 3)), 3) ),
	labels = list(BP = "Systolic Blood Pressure", method = "Measurement Device"),
	)
```

### Working on the JS comparison
```{r}
# consider on methods "J" and "S"
dat = subset(blood, subset = method != "R") # fixed-effects X_i with(subset(dat, subset = subject == "1"), model.matrix(BP ~ method)) # random-effects Z_i with(subset(dat, subset = subject == "1"), model.matrix( ~ method -1))
```
#### Fitting LME Models
```{r}
JS.roy1 = lme(BP ~ method-1, data = dat,random = list(subject=pdSymm(~ method-1)), weights=varIdent(form=~1|method),correlation = corSymm(form=~1 | subject/repl), method="ML")

```


### Permutation Testing
```{r}
permlme <- permmodels(model=JS.roy1, data=dat,nsim=1000)
summary(permlme)
```