---
title: "Blood Data with predictMeans package"
author: "Kevin O'Brien"
date: "Thursday, July 09, 2015"
output: html_document
---
```{r,echo=FALSE}
#using package NLME
library(nlme)
library(predictmeans)
source("data/BloodData.R")
```

### Working on the JS comparison
```{r,echo=FALSE}
blood = groupedData( BP ~ method | subject ,
  data = data.frame( BP = c(Blood), 
    subject = rep(seq(nrow(Blood)), ncol(Blood)),
		method = rep(c("J","R","S"), rep(nrow(Blood)*3, 3)),
		repl = rep(rep(c(1:3), rep(nrow(Blood), 3)), 3) ),
	labels = list(BP = "Systolic Blood Pressure", method = "Measurement Device"),
	)
```

### Working on the JS comparison
```{r,echo=FALSE}
# consider on methods "J" and "S"
dat = subset(blood, subset = method != "R") 
```
#### Fitting LME Models
```{r,echo=FALSE}
JS.roy1 = lme(BP ~ method-1, data = dat,random = list(subject=pdSymm(~ method-1)), weights=varIdent(form=~1|method),correlation = corSymm(form=~1 | subject/repl), method="ML")

```

### 1. CookD Function
This function produces Cook's distance plots for a linear model obtained from functions aov, lm,
glm, gls, lme, or lmer.

```{r}
CookD(JS.roy1,group="subject",idn=5,newwd=FALSE)
```

### 2. Residual Plots
```{r}
residplot(JS.roy1,"subject",newwd=FALSE)

```
