---
title: "Part4-DFBeta-Variants1-RoysTests"
author: "Kevin"
date: "March 27, 2016"
output: html_document
---

```{r,echo=FALSE}
#using package NLME
library(nlme)
library(MethComp)
library(lme4)
source("Functions.R")
source("data/BloodData.R")
```
```{r,echo=FALSE}
Blood<-data.frame(Blood)
mean(apply(Blood[1:3],1,mean))
mean(apply(Blood[4:6],1,mean))
mean(apply(Blood[7:9],1,mean))
```
```{r,echo=FALSE}
bias <- mean(apply(Blood[7:9],1,mean))-mean(apply(Blood[1:3],1,mean))
Blood[,4:6] <- Blood[,4:6] + matrix(rep(bias,255),nrow=85)
Blood[,7:9] <- Blood[,7:9] - matrix(rep(bias,255),nrow=85)
```
```{r,echo=FALSE}
mean(apply(Blood[1:3],1,mean))
mean(apply(Blood[4:6],1,mean))
mean(apply(Blood[7:9],1,mean))
Blood <- as.matrix(Blood)
```

```{r,echo=FALSE}
Blood <- as.matrix(Blood)
class(Blood)
```


### Working on the Blood Data
```{r,echo=FALSE}
Blood <- as.matrix(Blood)
blood = groupedData( BP ~ method | subject ,
  data = data.frame( BP = c(Blood), 
    subject = rep(seq(nrow(Blood)), ncol(Blood)),
    method = rep(c("J","R","S"), rep(nrow(Blood)*3, 3)),
  	repl = rep(rep(c(1:3), rep(nrow(Blood), 3)), 3) ),
	labels = list(BP = "Systolic Blood Pressure", method = "Measurement Device"),
	)
```
```{r}
head(blood)
```
### J vs R

Similar Data Sets R now have fixed bias.

```{r,echo=FALSE}
#pick out two of the three methods ( use J and J1 ) 
		
dat = subset(blood, subset = method != "S")


MCS1 = lme(BP ~ method-1, data = dat,
random = list(subject=pdSymm(~ method-1)),
weights=varIdent(form=~1|method),
correlation = corSymm(form=~1 | subject/repl), method="ML")

MCS2 = lme(BP ~ method-1, data = dat,
random = list(subject=pdCompSymm(~ method-1)),
weights = varIdent(form=~1|method),
correlation = corSymm(form=~1 | subject/repl), method="ML")


MCS3 = lme(BP ~ method-1, data = dat,
    random = list(subject=pdSymm(~ method-1)),
    weights=varIdent(form=~1|method), 
    correlation = corCompSymm(form=~1 | subject/repl), method="ML")

MCS4 = lme(BP ~ method-1, data = dat,
    random = list(subject=pdCompSymm(~ method-1)), 
    correlation = corCompSymm(form=~1 | subject/repl), method="ML")

```
```{r}
getVarCov(MCS1)
```

```{r}

getD(MCS1)
getSigma(MCS1)
getOmega(MCS1)
```
```{r}
anova(MCS1,MCS2)
anova(MCS1,MCS3)
anova(MCS1,MCS4)
```

### J vs Sredux
```{r}
#pick out two of the three methods ( use J and S ) 

dat = subset(blood, subset = method != "R")

```

```{r , echo=FALSE}

MCS1 = lme(BP ~ method-1, data = dat,
random = list(subject=pdSymm(~ method-1)),
weights=varIdent(form=~1|method),
correlation = corSymm(form=~1 | subject/repl), method="ML")

MCS2 = lme(BP ~ method-1, data = dat,
random = list(subject=pdCompSymm(~ method-1)),
weights = varIdent(form=~1|method),
correlation = corSymm(form=~1 | subject/repl), method="ML")


MCS3 = lme(BP ~ method-1, data = dat,
    random = list(subject=pdSymm(~ method-1)),
    weights=varIdent(form=~1|method), 
    correlation = corCompSymm(form=~1 | subject/repl), method="ML")

MCS4 = lme(BP ~ method-1, data = dat,
    random = list(subject=pdCompSymm(~ method-1)), 
    correlation = corCompSymm(form=~1 | subject/repl), method="ML")

```
```{r}

getD(MCS1)
getSigma(MCS1)
getOmega(MCS1)
```

```{r}
anova(MCS1,MCS2)
anova(MCS1,MCS3)
anova(MCS1,MCS4)
```



