---
title: "DFbetaAnalysis"
author: "Kevin O'Brien"
date: "Monday, August 24, 2015"
output: html_document
---
```{r}
#using package NLME
library(nlme)
library(MethComp)
library(lme4)
source("data/BloodData.R")
```
```{r}
Blood<-data.frame(Blood)
mean(apply(Blood[1:3],1,mean))
mean(apply(Blood[4:6],1,mean))
mean(apply(Blood[7:9],1,mean))

```


### Working on the Blood Data
```{r}
blood = groupedData( BP ~ method | subject ,
  data = data.frame( BP = c(Blood), 
    subject = rep(seq(nrow(Blood)), ncol(Blood)),
    method = rep(c("J","R","S"), rep(nrow(Blood)*3, 3)),
  	repl = rep(rep(c(1:3), rep(nrow(Blood), 3)), 3) ),
	labels = list(BP = "Systolic Blood Pressure", method = "Measurement Device"),
	)
```
#### Fit an LME4 Model to the data
```{r}
sbp.LME4 = lmer(BP ~ method-1 + (1 |subject ), data = blood,REML = FALSE)
summary(sbp.LME4)
#intervals(roy.LME4a)
```
#### Construct DFBETAs for LME4 Model

```{r}
library(influence.ME)
library(dplyr)

```
```{r}
MCS.LME4.inf  <- influence(sbp.LME4, "subject")
CDs<- cooks.distance(MCS.LME4.inf)
DFBs <- dfbetas(MCS.LME4.inf)
```
```{r}
case<- rownames(cooks.distance(MCS.LME4.inf))
CDdf <- data.frame(case,CDs)
CDdf<- arrange(CDdf,desc(CDs))
head(CDdf)
```

```{r}
case <- rownames(dfbetas(MCS.LME4.inf))
DFBetadf <- data.frame(case,DFBs)
Infldf <- inner_join(CDdf,DFBetadf)
Infldf<- arrange(Infldf,desc(CDs))
rownames(Infldf) <- Infldf$case
head(Infldf)
```
```{r}
pairs(Infldf[3:5],pch=18)
```
```{r}

plot(Infldf$methodJ,Infldf$methodR,col="red",pch=16,xlab=c("method J"),ylab=c("method R"))
abline(c(0,1))
```
```{r}
plot(Infldf$methodJ,Infldf$methodS,col="red",pch=16,xlab=c("method J"),ylab=c("method S"))
abline(c(0,1))
```
```{r}
plot(Infldf$methodR,Infldf$methodS,col="red",pch=16,xlab=c("method R"),ylab=c("method S"))
abline(c(0,1))

```
```{r}
par(mfrow=c(2,2))
plot(Infldf$methodJ,Infldf$methodR,col="red",pch=16,xlab=c("method J"),ylab=c("method R"))
abline(c(0,1))

plot(Infldf$methodJ,Infldf$methodS,col="red",pch=16,xlab=c("method J"),ylab=c("method S"))
abline(c(0,1))

plot(Infldf$methodR,Infldf$methodS,col="red",pch=16,xlab=c("method R"),ylab=c("method S"))
abline(c(0,1))

par(mfrow=c(1,1))
```

```{r}
corr.measures(Infldf$methodR,Infldf$methodS)
corr.measures(Infldf$methodJ,Infldf$methodS)
corr.measures(Infldf$methodR,Infldf$methodJ)
```
```{r}
attach(Infldf)
X<-methodJ;  Y<- methodS
A <- (X+Y)/2;  D<- (X-Y)
muD <- mean(D)
plot(A,D,pch=15,col="blue",cex=0.8)
abline(h=muD,col="blue",lwd=2)
title("Tukey Mean Difference Plots")
X<-methodJ;  Y<- methodR
A <- (X+Y)/2;  D<- (X-Y)
muD <- mean(D)
points(A,D,pch=16,col="red",cex=0.8)
abline(h=muD,col="red",lwd=2)



detach(Infldf) 

```
```{r}
library(car)
library(gvlma)
```
```{r}
modelRS = lm(methodR ~ methodS,data= Infldf)
modelJS = lm(methodJ ~ methodS,data= Infldf)
modelRJ = lm(methodR ~ methodJ,data= Infldf)
```
```{r}
summary(modelRS)$r.squared
summary(modelRJ)$r.squared
summary(modelJS)$r.squared
```
```{r}
outlierTest(modelJS)
outlierTest(modelRS)
outlierTest(modelRJ)
```
```{r}
Infldf[Infldf$case %in% c(78,80,36,22), ] 


```
```{r}
# D plot
par(mfrow=c(2,2))
plot(modelRJ, which=1)
plot(modelRJ, which=2)
plot(modelRJ, which=3)
plot(modelRJ, which=5)
par(mfrow=c(1,1))
```
```{r}
# Cook's D plot
par(mfrow=c(2,2))
plot(modelRS, which=1)
plot(modelRS, which=2)
plot(modelRS, which=3)
plot(modelRS, which=5)
par(mfrow=c(1,1))
```
```{r}
plot(modelRJ, which=4)

```
