---
title: "Leave subject Out - Study on Fixed Effects"
author: "Kevin O'Brien"
date: "Wednesday, August 05, 2015"
output: html_document
---

```{r}
#using package NLME
library(nlme)
library(ggplot2)
library(dplyr)
source("data/BloodData.R")
```
### Working on the JS comparison
```{r}
blood = groupedData( y ~ method | subject ,
  data = data.frame( y = c(Blood), 
    subject = rep(seq(nrow(Blood)), ncol(Blood)),
  	method = rep(c("J","R","S"), rep(nrow(Blood)*3, 3)),
		repl = rep(rep(c(1:3), rep(nrow(Blood), 3)), 3) ),
	labels = list(BP = "Systolic Blood Pressure", method = "Measurement Device"),
	)
```

```{r}
nsubj <- length(unique(blood$subject))
nmeth <- length(unique(blood$method))
outputdata=matrix(nrow=nsubj,ncol=nmeth)
blood=group_by(blood,method)
```



```{r}

for( i in 1:nsubj)
{
  bloodredux <- filter(blood, subject !=i)
  newdata <- summarize(bloodredux,mean(y))
  outputdata[i,] = t(newdata[,2])
}

```

```{r}
outputdata <-data.frame(outputdata)
names(outputdata)=c("J","S","R")
head(outputdata)
```
```{r}
pairs(outputdata,pch=18,bg = c("red", "green3", "blue"))
#pairs(outputdata)
```


```{r}
plot(outputdata$J,outputdata$R,pch=18)
#pairs(outputdata)
```
